#!/bin/sh
run_test=true
ul=`ulimit -s 2>/dev/null`
case "$ul" in
  unlimited)
    ulimit -s 1024 >/dev/null 2>&1 || run_test=false
    ;;
  ''|*[!0-9]*)
    run_test=true
    ;;
  *)
    if [ "$ul" -gt 4096 ] ; then
      ulimit -s 1024 >/dev/null 2>&1 || run_test=false
    fi
    ;;
esac

if $run_test; then
  ${program} > ${output} 2>&1;
else
  # The test is not actually run
  # We thus tell ocamltest the test output is equal to the reference file
  # so that the comparison between reference and output will still succeed
  echo output="${reference}" > ${ocamltest_response}
fi
